---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  securityContext:
      runAsUser: 0
  containers:
  - name: builder
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
