---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: operations-local
spec:
  securityContext:
      runAsUser: 0
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--verbosity=trace","--dockerfile=./Dockerfile", "--context=git://github.com/RobertoFlores/kaniko-demo.git#refs/heads/master",
            "--destination=robertrevolver/playground:7.0.0"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred-playground
        items:
          - key: .dockerconfigjson
            path: config.json

